CFLAGS += -DCONFIG_QCN_EXTN

OBJS+= \
	qcn_extns/240mhz.o \
	qcn_extns/driver_nl80211_extn.o \
	qcn_extns/ap_config_extn.o \
	qcn_extns/ctrl_iface_extn.o \
	qcn_extns/drv_callbacks_extn.o \
	qcn_extns/esp.o \
	qcn_extns/rnr.o \
	qcn_extns/macaddr.o

